### ISSUE TITLE
Ignore specific Activities when automatically instrumenting app starts

### ISSUE THREAD

**Issue by erawhctim** [bugsnag/bugsnag-android-performance#151]
### Description

App Start measurements don't align with anecdotal/real-world performance and average app start time seems to be lower than we expect it to be. Our app uses a separate activity as a loading screen before our main Activity is shown, and we suspect that automated Activity tracking for the first Activity is prematurely ending the App Start span, resulting in an inaccurate measurement. 

**Describe the solution you'd like**

- I'd like to have a way to specify which Activity should be used when determining the end of the App Start span.
- I'd like to continue to use automatic Activity tracking.
- I'd like to continue to see View Load spans for all Activities.

**Describe alternatives you've considered**

Refactoring our app loading sequence to remove the loading screen Activity and move to a truly single Activity architecture.

**Additional context**

I'm making assumptions around the behavior of the SDK and the results we're seeing here. 
If there's a way for me to confirm which Activity instance is being used to determine my App Start "end" time, I'd be happy to help triage this (as there's a chance that this might be working correctly from the start)

**Comment by gareththackeray** [comment]
Hi Mitch.  Once we release the span instance page you will be able to see the initial activity against an app start.  It looks like your hypothesis here is correct (I will email you the details).

Your idea around being able to specify which Activities signal the actual end of an App Start sounds good.  In fact after a little discussion we think it would make more sense to do the opposite and specify which Activities _shouldn't_ signal the end of an App Start.  We will schedule this into our roadmap and let you know when it's available.  

Please let us know what you think.

**Comment by erawhctim** [comment]
Great, thanks @gareththackeray. Both options sound like theu would solve the problem 👍 

Glad to know the new span page will give us more insight!

**Comment by erawhctim** [comment]
@gareththackeray Any concrete ETA on when this will get picked up?

**Comment by mclack** [comment]
Hi @erawhctim,
There isn’t currently a solid timeframe that we can share on when this work will be completed.

Are you now finding that having this feature would be additionally useful? Is your experience being limited without this feature?

**Comment by erawhctim** [comment]
Yeah, this essentially makes the app startup metric less useful because it becomes inaccurate (without larger architectural changes to our app). We still get value out of the Performance product as a whole, but have to consider the app startup metric with a grain of salt (knowing that it's inaccurate in it's current form)

**Comment by mclack** [comment]
Hi @erawhctim,

Thanks for the additional insight. I’ve fed this back to our product team, and will make sure to let you know as soon as we have any updates on this work.

**Comment by mclack** [comment]
Hi @erawhctim 
With our current plan, we are targeting this work will be completed by the end of the year. We will make sure to let you know once this has been done, along with any relevant updates prior to that.

**Comment by gareththackeray** [comment]
Hi @erawhctim this is now possible in v1.2.0.  See docs on [`doNotEndAppStart`](https://docs.bugsnag.com/performance/integration-guides/android/configuration-options/#do-not-end-app-start) config option.
