### ISSUE TITLE
AppCompat: Ignore specific Activities/Fragments when instrumenting screen loads

### ISSUE THREAD

**Issue by erawhctim** [bugsnag/bugsnag-android-performance#153]
### Description

We use a headless Fragment to facilitate some custom Activity-related UI _stuff_ and that Fragment gets picked up automatically by [the `FragmentActivityLifecycleCallbacks` observer](https://github.com/bugsnag/bugsnag-android-performance/blob/next/bugsnag-plugin-android-performance-appcompat/src/main/kotlin/com/bugsnag/android/performance/FragmentActivityLifecycleCallbacks.kt#L23-L29). 
We don't really care about seeing Screen Load data for that specific Fragment class.

**Describe the solution you'd like**

It'd be great if there was a way to modify the configuration with a list of Fragment names/classes to ignore during that screen load instrumentation. I suspect the same strategy could apply to ignoring specific Activities from the Scree Loads instrumentation as well

**Describe alternatives you've considered**

No alternatives considered. 
It's not _that_ big of a deal having those headless Fragments show up in our Screen Loads page; would just be a nice-to-have feature.

**Additional context**

N/A

**Comment by johnkiely1** [comment]
Hi @erawhctim, 

Thanks for raising, sounds like a reasonable request so I've passed it on to our product team for consideration.

**Comment by gareththackeray** [comment]
This is now possible in v1.2.0. See docs on [`doNotAutoInstrument`](https://docs.bugsnag.com/performance/integration-guides/android/configuration-options/#do-not-auto-instrument) config option.

**Comment by erawhctim** [comment]
Thanks @gareththackeray!
